fix: 修复小窗模式下滚动动画被连续打断的问题
linuxdeepin/dde-launcher pull request #136
Opened 2022-06-08 14:40 UTC by Maicss-chen

滚动事件每触发一次就会导致上次未结束的动画提前结束，导致滚动距离达不到预期目标，滚 轮滚动越快，列表滚动越慢 ，本次提交引入了一个平滑滚动条控件，替换了原有的滚动动画方案，解决了此问题。

2022-06-09 02:27 UTC, BLumia reviewed
我们的代码是遵循 Qt 的代码风格的，可以参阅 https://wiki.qt.io/Qt_Coding_Style。大致上是个别地方传参的时候逗号后面没加空格的问题。

其它暂时看着没什么问题了 👍

2022-06-09 02:27 UTC, BLumia commented on src/widgets/smoothscrollbar.cpp
> +    connect(m_propertyAnimation,&QPropertyAnimation::finished,this,&SmoothScrollBar::scrollFinish);
半角逗号后面要加空格

2022-06-09 02:54 UTC, Maicss-chen commented on src/widgets/smoothscrollbar.cpp
> +    connect(m_propertyAnimation,&QPropertyAnimation::finished,this,&SmoothScrollBar::scrollFinish);
好的，已经修改。
但是新的提交没有添加Log，自动检查报错，我需要重新创建一个pull request吗

2022-06-09 03:15 UTC, BLumia commented on src/widgets/smoothscrollbar.cpp
> +    connect(m_propertyAnimation,&QPropertyAnimation::finished,this,&SmoothScrollBar::scrollFinish);
你可以本地修改完后 `git commit -a --amend` 来修改上一个提交的内容的 :)

2022-06-09 03:18 UTC, BLumia commented on src/widgets/smoothscrollbar.cpp
> +  ,m_propertyAnimation(new QPropertyAnimation(this,"value",this))
😂 还有别的地方有这样的问题，可以一并改下

2022-06-09 03:42 UTC, Maicss-chen commented on src/widgets/smoothscrollbar.cpp
> +    connect(m_propertyAnimation,&QPropertyAnimation::finished,this,&SmoothScrollBar::scrollFinish);
感谢指导，已经更新啦，您看一下还有没有其它问题～

2022-06-09 04:20 UTC, Maicss-chen commented
@BLumia 自动构建好像失败了，我不知道是什么导致的这个问题，麻烦帮忙看一下～

2022-06-09 06:29 UTC, ut000966 commented
代码看了下，有两个方面的问题：
1 代码格式问题：空格问题
2 连续滚动效果太快了，不利于查找应用

2022-06-09 06:44 UTC, Maicss-chen commented
@ut000966 
1. 空格格式问题已经在第二个提交中修改。
2. 滚动太快并不是该方法的缺陷，应当通过调整滚动速度来解决，而这次提交解决的是原有问题导致滚动速度不正常。

例如：尝试快速滚动滚轮，再尝试慢速滚动滚轮，会发现后者滚动的范围更大，不符合正常逻辑，也导致滚动动画有类似卡顿效果。此方法中，使用任意速度滚动滚轮一定的距离，列表滚动的距离是一致的。因此该方法并是导致滚动过快的直接原因，而是滚动速度按照原有不正常的方案进行的调教导致的。

如果仍然有其它问题我还会继续完善 : )

2022-06-09 08:58 UTC, zccrs requested changes

2022-06-09 08:58 UTC, zccrs commented on src/widgets/smoothscrollbar.cpp
> + * Copyright (C) 2017 ~ 2018 Deepin Technology Co., Ltd.
这里的年份应该直接写 2022

2022-06-09 08:58 UTC, zccrs commented on src/widgets/smoothscrollbar.h
> + * Copyright (C) 2017 ~ 2018 Deepin Technology Co., Ltd.
同上

2022-06-09 08:58 UTC, zccrs commented on src/widgets/smoothscrollbar.cpp
> +SmoothScrollBar::SmoothScrollBar(QWidget *parent) : QScrollBar(parent)
````
SmoothScrollBar::SmoothScrollBar(QWidget *parent)
    : QScrollBar(parent)
    , m_propertyAnimation(new QPropertyAnimation(this, "value", this))
````
    
这样比较整洁

2022-06-09 08:58 UTC, zccrs commented on src/widgets/smoothscrollbar.cpp
> +
这个空行不需要

2022-06-09 08:58 UTC, zccrs commented on src/widgets/smoothscrollbar.h
> +    void scrollFinish();
scrollFinished

2022-06-09 08:58 UTC, zccrs commented on src/view/applistview.cpp
> -    // 解决蓝牙连接时触摸板斜对角方向双指按住滑动时滑条滚动异常问题
直接删掉这一段不确定是否有问题，可以 blame 看下这部分代码之前是为了解决什么问题的

2022-06-09 08:58 UTC, zccrs commented on src/widgets/smoothscrollbar.cpp
> +    if (m_targetValue > maximum()) {
m_targetValue = qBound(minimum(), m_targetValue, maximum())

2022-06-09 08:58 UTC, zccrs commented on src/widgets/smoothscrollbar.cpp
> +    m_targetValue += value;
是不是应该放到判断条件之前？

2022-06-09 09:07 UTC, Maicss-chen commented on src/widgets/smoothscrollbar.cpp
> +    m_targetValue += value;
这个是故意这么写的，如果放到之前的话就会导致滚动到上下边缘会减速，这么些会有类似撞停的效果

2022-06-09 09:11 UTC, zccrs commented on src/widgets/smoothscrollbar.cpp
> +    m_targetValue += value;
嗯，可以加个注释说明一下，因为从前面那几行代码看，意图是限制 m_targetValue 的取值范围，但是紧接着就给 m_targetValue 多加了 value，给人的第一感觉是这里增加的value会导致超出上面的取值范围，会觉得这里的逻辑有些问题。

2022-06-09 09:13 UTC, zccrs commented on src/widgets/smoothscrollbar.cpp
> + * Copyright (C) 2017 ~ 2018 Deepin Technology Co., Ltd.
直接写 2022, 新建的文件的 copyright 的时间是这个文件的创建年份

2022-06-09 09:26 UTC, Maicss-chen commented on src/widgets/smoothscrollbar.cpp
> +    m_targetValue += value;
好的，已经修改了

2022-06-09 09:28 UTC, zccrs requested changes

2022-06-09 09:28 UTC, zccrs commented on src/widgets/smoothscrollbar.cpp
> +    ,m_propertyAnimation(new QPropertyAnimation(this, "value", this))
逗号后边应该有个空格，跟上一行是对齐的

2022-06-09 09:31 UTC, Maicss-chen commented on src/widgets/smoothscrollbar.cpp
> +    ,m_propertyAnimation(new QPropertyAnimation(this, "value", this))
OK

2022-06-10 02:01 UTC, BLumia commented
看更新后的代码的 debian 打包检查在跑测试的步骤有个段错误，点 Details 可以看日志。建议手动检查下单元测试是否有问题？

2022-06-10 02:46 UTC, Maicss-chen commented
> 看更新后的代码的 debian 打包检查在跑测试的步骤有个段错误，点 Details 可以看日志。建议手动检查下单元测试是否有问题？

我这里测试可以通过，是否是其它问题导致的？

2022-06-15 02:14 UTC, zccrs requested changes

2022-06-15 02:14 UTC, zccrs commented on src/view/applistview.cpp
> +    /*
这里是不是不应该修改？

2022-06-15 02:14 UTC, zccrs commented on src/widgets/smoothscrollbar.cpp
> + * Copyright (C) 2022 Deepin Technology Co., Ltd.
把 Deepin 换成 UnionTech，下面的文件也一样。另外要加上你个人的 copyright

2022-06-15 02:14 UTC, zccrs commented on src/widgets/smoothscrollbar.h
> + * Copyright (C) 2022 Deepin Technology Co., Ltd.
同上

2022-06-15 03:55 UTC, BLumia commented on src/widgets/smoothscrollbar.cpp
> + * Copyright (C) 2022 Deepin Technology Co., Ltd.
把 Deepin 换成 UnionTech 的事情不应该由非 deepin/UnionTech 的员工来做吧。只加自己的 copyright 就可以了

2022-06-15 03:58 UTC, BLumia commented on src/widgets/smoothscrollbar.cpp
> + * Copyright (C) 2022 Deepin Technology Co., Ltd.
```suggestion
 * Copyright (C) 2022 Deepin Technology Co., Ltd.
 * Copyright (C) 2022 Maicss <maicss@126.com>
```

供参考

2022-06-15 05:03 UTC, zccrs commented on src/widgets/smoothscrollbar.cpp
> + * Copyright (C) 2022 Deepin Technology Co., Ltd.
可以

2022-06-15 05:42 UTC, zccrs commented
/+1

2022-06-15 05:43 UTC, zccrs reviewed
OK

2022-08-11 11:55 UTC, ssk-wh commented
style: 整理代码

2022-08-11 11:56 UTC, ssk-wh commented
style: 整理代码
这个有两个提交，可以压缩成一笔

2022-08-12 01:18 UTC, BLumia commented
@Maicss-chen 方便的话可以把这几个 commit squash 到一个里，不方便的话告诉我们这边下，我们帮你调整也行 :)

2022-08-15 05:58 UTC, wentaosong1993 commented on src/view/applistview.cpp
> +    , m_scrollbar(new SmoothScrollBar)
m_scrollbar 需要指定父对象。

2022-08-18 01:39 UTC, wentaosong1993 commented
> 滚动事件每触发一次就会导致上次未结束的动画提前结束，导致滚动距离达不到预期目标，滚 轮滚动越快，列表滚动越慢 ，本次提交引入了一个平滑滚动条控件，替换了原有的滚动动画方案，解决了此问题。

有一个地方需要修改下，请处理...

2022-08-18 02:21 UTC, Maicss-chen commented on src/view/applistview.cpp
> +    , m_scrollbar(new SmoothScrollBar)
已经修改

2022-08-18 02:22 UTC, Maicss-chen commented
> @Maicss-chen方便的话可以把这几个犯下到里边，不方便告诉我们下一个，我们帮你调也行:)

好的，已经修改了。

2022-08-18 02:24 UTC, Maicss-chen commented
I have read the CLA Document and I hereby sign the CLA.

2022-08-24 02:58 UTC, wentaosong1993 approved these changes
目前来看，没有其他问题，同意合入。

2022-08-24 03:12 UTC, ssk-wh submitted a review, later dismissed

2022-08-24 06:58 UTC, BLumia commented
@Maicss-chen 应该可以合并了，可以回复个 `merge` 试试看了~

2022-08-25 10:39 UTC, Maicss-chen commented
/merge

2022-08-25 10:41 UTC, Maicss-chen commented
> @Maicss-chen 应该可以合并了，可以回复个 `/merge` 试试看了~

看起来不能自动合并。

2022-08-25 10:52 UTC, Maicss-chen commented
/merge

2022-08-25 10:59 UTC, BLumia commented
可能是因为 @zccrs 没有重新给 review 结果.

2022-08-25 11:02 UTC, BLumia approved these changes

2022-08-25 11:09 UTC, Maicss-chen commented
/merge

2022-08-25 11:12 UTC, BLumia commented
应该确实是因为 @zccrs 没更新 review 状态，导致之前的修改请求还生效。

我直接合并掉吧。

2022-08-25 11:12 UTC, BLumia commented
/merge

2022-08-26 05:31 UTC, zccrs requested changes

2022-08-26 05:31 UTC, zccrs commented on src/view/applistview.cpp
> +    /*
这个改动没必要呀

2022-08-26 06:33 UTC, Maicss-chen commented on src/view/applistview.cpp
> +    /*
改了，但
fix: 应用选中状态优化 (#315)
这个提交不知道为啥也进来了。
git实在不太熟练，我尽力了。。

2022-08-26 06:50 UTC, BLumia commented on src/view/applistview.cpp
> +    /*
额，大概是你界面上点的是 merge 而不是 rebase 😂 

如果你本地没进行 merge 的话，可以重新 push -f 推一下，然后不在 PR 的页面里点更新。

或者实在不熟悉的话，告诉我下我这边帮你操作也行。

另外也欢迎来 https://t.me/deepin_community ，可能指导问题会方便一些（（

2022-08-26 07:57 UTC, zccrs approved these changes

2022-08-26 07:58 UTC, Maicss-chen commented
/merge

2022-08-26 07:58 UTC, merged